- name: 'Provision Image'
  hosts: 'all'
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"
        
    - name: Install nginx
      apt:
        name: nginx
        update_cache: true
        state: latest
