name: Test project
run-name: ${{ github.actor }} testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: executing
          run: |
          ${{ github.workspace }}/website_deploy.sh
      - name: delete terraform
          run: |
          cd ${{ github.workspace }}/terraform
          terraform destroy
        
