name: Test project
run-name: ${{ github.actor }} testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        working-directory: terraform
        run: |
          ls
      - name: executing
        run: |
          ${{ github.workspace }}/website_deploy.sh
      - name: executing
        run: |
          cd ${{ github.workspace }}/terraform
          terraform destroy
